name: Deploy theme to WP Engine

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'wp/wp-content/themes/lifespan-psychiatry-2024/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy theme to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: ${{ vars.WPE_ENV || secrets.WPE_ENV }}
          SRC_PATH: 'wp/wp-content/themes/lifespan-psychiatry-2024/'
          REMOTE_PATH: 'wp-content/themes/lifespan-psychiatry-2024/'
          PHP_LINT: TRUE
          FLAGS: -azvr --inplace --delete --exclude=.* --exclude-from=.deployignore
          CACHE_CLEAR: TRUE

